services:
  caddy:
    build:
      context: ./dockerfiles
      dockerfile: Caddy_Dockerfile
      labels:
        version: "1.0.0"
        description: "Caddy with Cloudflare DNS plugin"
    image: caddy-custom:1.0.0    
    container_name: caddy
    restart: unless-stopped
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./container_config/caddy:/etc/caddy:ro
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy-net

  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./container_config/homepage:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.parzezal.dev,homepage.parzezal.dev:3000
    networks:
      - caddy-net

  prometheus:
    command:
     - --config.file=/etc/prometheus/prometheus.yml
     - --storage.tsdb.retention.time=30d
     - --storage.tsdb.retention.size=5GB
    image: prom/prometheus:v3.13.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./container_config/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - caddy-net

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - caddy-net 

networks:
  caddy-net:
    name: caddy-net

volumes:
  caddy_data:
  caddy_config:
  prom_data:
  grafana_data: 